ProjekatCloud/PortfolioService/Controllers/CryptoController.cs
using Common;
using Microsoft.Ajax.Utilities;
using Microsoft.WindowsAzure.Storage.Queue;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace PortfolioService.Controllers
{
    public class CryptoController : Controller
    {
        // GET: Crypo
        CryptoDataRepository client = new CryptoDataRepository();
        AlarmDataRepository alarms = new AlarmDataRepository();
        AlarmDoneDataRepository alarmdone = new AlarmDoneDataRepository();
        public async Task<ActionResult> Index()
        {
            //Dictionary<string, double> dictionary = await client.GetTickerAsync();
            //ViewBag.data = dictionary.Values;
            //ViewBag.datastring = dictionary.Keys;
            //foreach (var valuta in dictionary)
            //{
            //    DateTime time = DateTime.Now;
            //    client.AddCrypto(new Crypto(time.ToString()) { Currency = valuta.Key, datumIVrijeme = time, Email="A", StartValue=valuta.Value, EndValue=100});
            //}
            return View();
        }

        public ActionResult GetCurrencyForUser()
        {
            User user = (User)HttpContext.Application["user"];
            if (user != null)
            {
                List<Crypto> lista = client.GetAllCryptoForEmail(user.RowKey);
                Dictionary<string, int> dictionary = new Dictionary<string, int>();
                foreach (Crypto c in lista)
                {
                    if (dictionary.Keys.Contains(c.Currency))
                    {
                        dictionary[c.Currency] += c.Quantity;
                    }
                    else
                    {
                        dictionary[c.Currency] = c.Quantity;
                    }
                }
                ViewBag.Currency = dictionary;
            }
            else
            {
                ViewBag.Currency = new Dictionary<string, int>();
            }
            return View();
        }
        public async Task<ActionResult> BuyOrSell()
        {
            if (TempData["ind"] == null || TempData["ind"].ToString() != "filter")
            {
                List<PriceInfo> prices = await client.GetTickerAllAsync();
                List<string> symbols = new List<string>();
                foreach (var p in prices)
                {
                    symbols.Add(p.Symbol);
                }
                IQueryable<Crypto> list = client.RetrieveAllCurrency();
                foreach (var v in list)
                {
                    v.EndValue = (prices.Where(p => p.Symbol == v.Currency).FirstOrDefault()).Price;
                    client.UpdateCrypto(v);
                }
                TempData["Filter"] = prices.ToList();
                TempData["Symbols"] = symbols.ToList();
                ViewBag.Symbols = symbols;
                ViewBag.AllInfo = prices;

            }
            else
            {
                ViewBag.AllInfo = (List<PriceInfo>)TempData["FilterList"];
                ViewBag.Symbols = (List<string>)TempData["Symbols"];
                TempData["ind"] = "base";
            }
            return View();
        }

        public async Task<ActionResult> Filter(string filter)
        {
            List<PriceInfo> filters = (List<PriceInfo>)TempData["Filter"];
            List<PriceInfo> pov = new List<PriceInfo>();
            foreach(var v in filters)
            {
                if (v.Symbol.Contains(filter))
                {
                    pov.Add(v);
                }
            }

            TempData["FilterList"] = pov.ToList();
            TempData["ind"] = "filter";
            return RedirectToAction("BuyOrSell");
        }
        public async Task<ActionResult> BuyOrSellCrypto(CryptoDTO crypto)
        {
            try
            {
                double value = await client.GetTickerForCurrencyAsync(crypto.Currency);
                int quantity = Convert.ToInt32(crypto.Price / value);
                if (quantity > 0)
                {
                    if (crypto.Type == "K")
                    {
                        Crypto c = new Crypto(DateTime.Now.ToString()) { Currency = crypto.Currency, datumIVrijeme = crypto.Date, Email = ((User)HttpContext.Application["user"]).RowKey, StartValue = value, EndValue = value, Quantity = quantity, BuyOrSell = crypto.Type };
                        client.AddCrypto(c);
                        ViewBag.Kupljeno = "Uspesno kupljeno";
                    }
                    else if (crypto.Type == "P")
                    {
                        Crypto c = new Crypto(DateTime.Now.ToString()) { Currency = crypto.Currency, datumIVrijeme = crypto.Date, Email = ((User)HttpContext.Application["user"]).RowKey, StartValue = value, EndValue = value, Quantity = quantity, BuyOrSell = crypto.Type };
                        client.AddCrypto(c);
                        client.GetAllCryptoForSell(crypto.Currency, crypto.Price.ToString(), ((User)HttpContext.Application["user"]).RowKey);
                        ViewBag.Kupljeno = "Uspesno ste prodali valutu";
                    }
                }
                else
                {
                    ViewBag.Kupljeno = "Nemate dovoljno novca za ovu transakciju";
                }

            }catch(Exception e)
            {
                Console.WriteLine(e.Message);
            }

            return View();
        }
        public async Task<ActionResult> AddAlarm(CryptoDTO crypto)
        {
            try
            {
                User user = (User)HttpContext.Application["user"];
                if (user != null)
                {
                    alarms.AddAlarm(new Alarm() { Currency = crypto.Currency, Email = user.RowKey, AlarmValue = crypto.Price });
                }

            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }

            return RedirectToAction("UpdateAlarmView");
        }

        public async Task<ActionResult> DeleteCrypto()
       {
            User user = (User)HttpContext.Application["user"];
            if (user != null)
            {
                List<Crypto> currency = client.GetAllCryptoForEmail(user.RowKey);
                List<string> lista = new List<string>();
                foreach (var c in currency)
                {

                    lista.Add(c.Currency);
                }
                List<string> novalista = lista.Distinct().ToList();
                ViewBag.Symbols = novalista;
                ViewBag.Currency = currency;
            }
            else
            {
                ViewBag.Symbols = new List<string>();
                ViewBag.Currency = new List<Crypto>();
            }
            return View();
       }


        public ActionResult DeleteCurrency(CurrencyNameDTO currency)
        {
            User user = (User)HttpContext.Application["user"];
            if (user != null)
            {
                try
                {
                    client.RemoveCrypto(user.RowKey, currency.Name);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.Message);
                }
            }
            return RedirectToAction("DeleteCrypto");
        }

        public ActionResult DeletePartialCrypto(string deleteCrypto)
        {
            User user = (User)HttpContext.Application["user"];
            if (user != null)
            {
                try
                {
                    client.RemoveCryptoId(deleteCrypto);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.Message);
                }
            }
            return RedirectToAction("DeleteCrypto");
        }

        public ActionResult ChooseCurrencyToShow()
        {
            User user = (User)HttpContext.Application["user"];
            try
            {
                List<Crypto> currency = client.GetAllCryptoForEmail(user.RowKey);
                List<string> lista = new List<string>();
                foreach (var c in currency)
                {
                    lista.Add(c.Currency);
                }
                List<string> novalista = lista.Distinct().ToList();
                ViewBag.Symbols = novalista;
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
            }
      
            if (TempData["result"] != null)
            {
                ViewBag.Result = TempData["result"];
                ViewBag.Currency = TempData["currency"];
                ViewBag.NotResult = false;
            }
            else
            {
                ViewBag.NotResult = true;
            }
            TempData["result"] = null;
            TempData["currency"] = null;
            return View();
        }

        public async Task<ActionResult> ViewProfitOrLoss(CurrencyNameDTO currency)
        {
            User user = (User)HttpContext.Application["user"];
            List<Crypto> list = client.GetAllCryptoForEmailCurrency(user.RowKey, currency.Name);
            double value = await client.GetTickerForCurrencyAsync(currency.Name);
            double result = 0;
            foreach (var v in list)
            {
                result += (value - v.StartValue)*v.Quantity;
                v.EndValue = value;
                client.UpdateCrypto(v);
            }
            TempData["result"] = result;
            TempData["currency"] = currency.Name;
            return RedirectToAction("ChooseCurrencyToShow");
        }

        public async Task<ActionResult> ViewEntireProfitOrLoss()
        {
            User user = (User)HttpContext.Application["user"];
            List<Crypto> list = new List<Crypto>();
            list = client.GetAllCryptoForEmail(user.RowKey);
            List<string> names = new List<string>();

ProjekatCloud/PortfolioService/Controllers/HomeController.cs
using Common;
using Microsoft.Azure;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PortfolioService.Controllers
{
    public class HomeController : Controller
    {
        public static UserDataRepository repo = new UserDataRepository();
        //public static LogDataRepository repodata = new LogDataRepository();
        public ActionResult Index()
        {
            //repodata.AddLog(new Log("string"));
            return View();
        }
       

        [HttpPost]
        public ActionResult Register(String Name, String LastName, HttpPostedFileBase file, String Email, String Password, String Address, String City, String Country, String PhoneNumber)
        {
            try
            {
                if (repo.Exists(Email))
                {
                    return View("Error");
                }

                // kreiranje blob sadrzaja i kreiranje blob klijenta
                string uniqueBlobName = string.Format("image_{0}", Email);
                var storageAccount = CloudStorageAccount.Parse(CloudConfigurationManager.GetSetting("DataConnectionStringBlob"));
                CloudBlobClient blobStorage = storageAccount.CreateCloudBlobClient();
                CloudBlobContainer container = blobStorage.GetContainerReference("vezba");
                CloudBlockBlob blob = container.GetBlockBlobReference(uniqueBlobName);
                blob.Properties.ContentType = file.ContentType;
                // postavljanje odabrane datoteke (slike) u blob servis koristeci blob klijent
                blob.UploadFromStream(file.InputStream);
                // upis studenta u table storage koristeci StudentDataRepository klasu
                User entry = new User(Email) { Name = Name, LastName = LastName, PhotoUrl = blob.Uri.ToString(), Password = Password, Address=Address, City=City, Country=Country, PhoneNumber=PhoneNumber   /*, ThumbnailUrl = blob.Uri.ToString() */};
                repo.AddUser(entry);
                ViewBag.user = entry;
                HttpContext.Application["user"] = entry;
                //CloudQueue queue = QueueHelper.GetQueueReference("vezba");
                //queue.AddMessage(new CloudQueueMessage(RowKey), null, TimeSpan.FromMilliseconds(30));

                //return RedirectToAction("ShowAllUsers");
                return View("MyProfile");
            }
            catch
            {
                return View("Index");
            }
        }

        public ActionResult ShowAllUsers()
        {
            return View(repo.RetrieveAllUsers());
        }

        public ActionResult LogIn()
        {
            return View();
        }

        public ActionResult Logout()
        {
            HttpContext.Application["user"] = null;
            return RedirectToAction("LogIn");
        }

        public ActionResult LogInWithParameters(string email, string password)
        {
            User user = repo.ExistsUser(email, password);
            if(user != null)
            {
                HttpContext.Application["user"] = user;
                ViewBag.user = user;
                return View("MyProfile");
            }
            else
            {
                ViewBag.errorLogIn = "Neispravni kredencijali";
                return View("LogIn");
            }
        }

        public ActionResult MyProfile()
        {
            ViewBag.user = (User)HttpContext.Application["user"];
            return View("MyProfile");
        }

       
    }
}

ProjekatCloud/PortfolioService/Controllers/UserController.cs
using Common;
using Microsoft.Azure;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using System;
using System.Web;
using System.Web.Mvc;

namespace PortfolioService.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Update(String Name, String LastName, HttpPostedFileBase file, String RowKey, String Password, String Address, String City, String Country, String PhoneNumber)
        {

            string uniqueBlobName = string.Format("image_{0}", file);
            var storageAccount = CloudStorageAccount.Parse(CloudConfigurationManager.GetSetting("DataConnectionStringBlob"));
            CloudBlobClient blobStorage = storageAccount.CreateCloudBlobClient();
            CloudBlobContainer container = blobStorage.GetContainerReference("vezba");
            CloudBlockBlob blob = container.GetBlockBlobReference(uniqueBlobName);
            if (file != null)
            {
                blob.Properties.ContentType = file.ContentType;
                // postavljanje odabrane datoteke (slike) u blob servis koristeci blob klijent

                blob.UploadFromStream(file.InputStream);
                // upis studenta u table storage koristeci StudentDataRepository klasu

                HomeController.repo.UpdateUser(new Common.User(RowKey) { Name = Name, LastName = LastName, PhotoUrl = blob.Uri.ToString(), Password = Password, Address = Address, City = City, Country = Country, PhoneNumber = PhoneNumber, ETag = "*" });
            }
            else
            {
                User userold = (User)HttpContext.Application["user"];
                HomeController.repo.UpdateUser(new Common.User(RowKey) { Name = Name, LastName = LastName, PhotoUrl=userold.PhotoUrl, Password = Password, Address = Address, City = City, Country = Country, PhoneNumber = PhoneNumber, ETag = "*" });
            }

           
           
            User u = (User)HttpContext.Application["user"];
            if (u != null)
            {
                HttpContext.Application["user"] = HomeController.repo.ExistsUser(RowKey, u.Password);
                ViewBag.user = (User)HttpContext.Application["user"];
            }
            else
            {
                ViewBag.user = new User();
            }
            return RedirectToAction("MyProfile", "Home");
        }
    }
}

ProjekatCloud/PortfolioService/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@model Common.User
    @{
        ViewBag.Title = "Registruj se"; }
    <h2>Dodaj novog korisnika</h2>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    @using (Html.BeginForm("Register", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.ValidationSummary(true)
<fieldset>
    <legend>Student</legend>
    <div class="editor-label">
        @Html.LabelFor(model => model.Name)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Name) @Html.ValidationMessageFor(model => model.Name)
    </div>
    <div class="editor-label">
        @Html.LabelFor(model => model.LastName)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.LastName) @Html.ValidationMessageFor(model => model.LastName)
    </div>
    <div class="editor-label">
        @Html.LabelFor(model => model.Address)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Address) @Html.ValidationMessageFor(model => model.Address)
    </div>
    <div class="editor-label">
        @Html.LabelFor(model => model.City)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.City) @Html.ValidationMessageFor(model => model.City)
    </div>
    <div class="editor-label">
        @Html.LabelFor(model => model.Country)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Country) @Html.ValidationMessageFor(model => model.Country)
    </div>
    <div class="editor-label">
        @Html.LabelFor(model => model.PhoneNumber)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.PhoneNumber) @Html.ValidationMessageFor(model => model.PhoneNumber)
    </div>
    <div class="editor-label">
        @Html.LabelFor(model => model.Email)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Email) @Html.ValidationMessageFor(model => model.Email)
    </div>
    <div class="editor-label">
        @Html.LabelFor(model => model.Password)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Password) @Html.ValidationMessageFor(model => model.Password)
    </div>
    <input type="file" id="studentPicture" name="file" />
    <p>
        <input type="submit" value="Create" />
    </p>
</fieldset>
    }
    <div>
        @Html.ActionLink("Log In", "LogIn")
    </div>

ProjekatCloud/PortfolioService/Views/Home/LogIn.cshtml
@{
    ViewBag.Title = "LogIn Page";
}
@model Common.User
@{
    ViewBag.Title = "LogIn"; }
<h2>Prijavi se</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@using (Html.BeginForm("LogInWithParameters", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
<fieldset>
    <legend>Student</legend>
    <div class="editor-label">
        @Html.LabelFor(model => model.Email)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Email) @Html.ValidationMessageFor(model => model.Email)
    </div>
    <div class="editor-label">
        @Html.LabelFor(model => model.Password)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Password) @Html.ValidationMessageFor(model => model.Password)
    </div>
    <p>
        <input type="submit" value="LogIn" />
    </p>
    <p>
        @ViewBag.errorLogIn
    </p>
</fieldset>
}
<div>
    @Html.ActionLink("Register", "Index")
</div>
<div>
    @Html.ActionLink("Logout", "Logout")
</div>

ProjekatCloud/PortfolioService/Views/Home/MyProfile.cshtml
<h2>MyProfile</h2>
@model Common.User
@{
    ViewBag.Title = "Izmeni profil"; }
<h2>Moj profil</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@using (Html.BeginForm("Update", "User", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <fieldset>
        <legend>Student</legend>
        <table>

            <tr>
                <td>
                    <label>Name:</label>
                </td>
                <td>
                    <input value="@ViewBag.user.Name" type="text" name="Name" required />
                </td>
            </tr>
            <tr>
                <td>
                    <label>LastName:</label>
                </td>
                <td>
                    <input value="@ViewBag.user.LastName" type="text" name="LastName" required />
                </td>
            </tr>
            <tr>
                <td>
                    <label>Email:</label>
                </td>
                <td>
                    <input value="@ViewBag.user.RowKey" type="text" name="RowKey" readonly />
                </td>
            </tr>
            <tr>
                <td>
                    <label>Password:</label>
                </td>
                <td>
                    <input value="@ViewBag.user.Password" type="text" name="Password" readonly />
                </td>
            </tr>
            <tr>
                <td>
                    <label>Address:</label>
                </td>
                <td>
                    <input value="@ViewBag.user.Address" type="text" name="Address" required />
                </td>
            </tr>
            <tr>
                <td>
                    <label>City:</label>
                </td>
                <td>
                    <input value="@ViewBag.user.City" type="text" name="City" required />
                </td>
            <tr>
                <td>
                    <label>Country:</label>
                </td>
                <td>
                    <input value="@ViewBag.user.Country" type="text" name="Country" required />
                </td>
            <tr>
                <td>
                    <label>PhoneNumber:</label>
                </td>
                <td>
                    <input value="@ViewBag.user.PhoneNumber" type="text" name="PhoneNumber" required />
                </td>

            </tr>
            <tr>
                <td>
                    <label>Image:</label>
                </td>
                <td>
                    <img src="@Url.Content(ViewBag.user.PhotoUrl)" alt="User Photo" style="width: 50px; height: 50px;" />
                </td>
                <td>
                    <input type="file" id="studentPicture" name="file" />
                </td>
            </tr>
            <tr>
                <td>
                    <input type="submit" value="Update" />
                </td>
            </tr>
        </table>
    </fieldset>
}

@Html.ActionLink("Kripto", "Index", "Crypto")
<br />

@Html.ActionLink("Kupi ili prodaj", "BuyOrSell", "Crypto")
<br />

@Html.ActionLink("Obrisi kriptovalutu", "DeleteCrypto", "Crypto")
<br />

@Html.ActionLink("Izaberi kriptovalutu za ukupan profit", "ChooseCurrencyToShow", "Crypto")
<br />

@Html.ActionLink("Prikazi ukupan profit", "ViewEntireProfitOrLoss", "Crypto")
<br />

@Html.ActionLink("Prikazi moje dostignute alarme", "UpdateAlarmView", "Crypto")
<br />

@Html.ActionLink("Logout", "Logout", "Home")
<br />

ProjekatCloud/PortfolioService/Views/Home/ShowAllUsers.cshtml
@model IEnumerable<Common.User>
@{
    ViewBag.Title = "ShowAllUsers"; }
<h2>
    Index
</h2>
<table>
    <tr>
        <th>
            Index
        </th>
        <th>
            Name
        </th>
        <th>
            LastName
        </th>
        <th>
            Photo
        </th>
        <th>
        </th>
    </tr> @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RowKey)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                <img src="@item.PhotoUrl" />
            </td>
        </tr>
    }
</table>